### ISSUE TITLE
Browser or File related issues ?

### ISSUE THREAD

**Issue by p1nh0** [Sonoscopia/Transarkiv#61]
On Chrome 49.0.2623.112 (64-bit)

p5.js:11952 The deviceorientation event is deprecated on insecure origins, and support will be removed in the future. You should consider switching your application to a secure origin, such as HTTPS. See https://goo.gl/rStTGz for more details.
p5.js:11952 The devicemotion event is deprecated on insecure origins, and support will be removed in the future. You should consider switching your application to a secure origin, such as HTTPS. See https://goo.gl/rStTGz for more details.
p5.sound_.js:956 GET http://sonoscopia.pt/wp-content/uploads/2016/04/Discuss%C3%A3o-a-janela.mp3 404 (Not Found)p5.SoundFile.load @ p5.sound_.js:956p5.SoundFile @ p5.sound_.js:838p5.loadSound @ p5.sound_.js:890Player @ Player.js:63setup @ sketch.js:27(anonymous function) @ p5.js:11769_runIfPreloadsAreDone @ p5.js:11725(anonymous function) @ p5.js:11710p5 @ p5.js:11976_globalInit @ p5.js:8482
p5.sound_.js:941 Unable to load http://sonoscopia.pt/wp-content/uploads/2016/04/Discussão-a-janela.mp3. The request status was: 404 (Not Found)
 The error stack trace includes: 
loadSound
    at new Player (http://sonoscopia.pt/wp-content/uploads/2016/04/Player.js:63:16)
    at setup (http://sonoscopia.pt/wp-content/uploads/2016/04/sketch.js:27:18)request.onload @ p5.sound_.js:941

PS: could be a problem with the actual file!

**Comment by p1nh0** [comment]
plus this file:

p5.sound_.js:956 GET http://sonoscopia.pt/wp-content/uploads/2016/04/Gina-hist%C3%B3rias-de-vidaa.mp3 404 (Not Found)p5.SoundFile.load @ p5.sound_.js:956p5.SoundFile @ p5.sound_.js:838p5.loadSound @ p5.sound_.js:890Player @ Player.js:63LeftMenu.clicked @ LeftMenu.js:43mousePressed @ sketch.js:79p5._onmousedown @ p5.js:18840
p5.sound_.js:941 Unable to load http://sonoscopia.pt/wp-content/uploads/2016/04/Gina-histórias-de-vidaa.mp3. The request status was: 404 (Not Found)
 The error stack trace includes: 
loadSound
    at new Player (http://sonoscopia.pt/wp-content/uploads/2016/04/Player.js:63:16)
    at LeftMenu.clicked (http://sonoscopia.pt/wp-content/uploads/2016/04/LeftMenu.js:43:25)
    at mousePressed (http://sonoscopia.pt/wp-content/uploads/2016/04/sketch.js:79:8)request.onload @ p5.sound_.js:941
